apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backstage-setup-app
  namespace: argocd
spec:
  destination:
    name: in-cluster
  project: tanuu
  source:
    directory:
      jsonnet: {}
      recurse: true
    path: setup/backstage
    # repoURL: https://github.com/tanuuidp/tanuu.git
    repoURL: https://github.com/daniel-vaskivaara/tanuu.git
    targetRevision: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true