apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: events-setup-app
  namespace: argocd
spec:
  destination:
    name: in-cluster
  project: tanuu
  source:
    directory:
      jsonnet: {}
      recurse: true
    path: setup/argo-events
    repoURL: https://github.com/tanuuidp/tanuu.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true