apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/issuer: backstage
    cert-manager.io/issuer-kind: Issuer
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "30"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "1800"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "1800"
  labels:
    app: backstage
  name: backstage
  namespace: backstage
spec:
  rules:
  - host: backstage.tanuu.fi
    http:
      paths:
      - backend:
          service:
            name: backstage
            port:
              number: 80
        pathType: ImplementationSpecific
  tls:
  - hosts:
    - backstage.tanuu.fi
    secretName: tls-backstage-ingress
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  labels:
    app: backstage
  name: backstage
  namespace: backstage
spec:
  acme:
    email: certs@allred.fi
    preferredChain: ""
    privateKeySecretRef:
      name: letsencrypt-production
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
    - http01:
        ingress:
          class: nginx
