apiVersion: v1
kind: Service
metadata:
  name: argocd-incoming
  namespace: argocd
spec:
  ports:
  - name: web
    nodePort: 30081
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app.kubernetes.io/name: argocd-server
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: argo-incoming
  namespace: argo
spec:
  ports:
  - name: web
    nodePort: 30082
    port: 80
    protocol: TCP
    targetPort: 2746
  selector:
    app.kubernetes.io/name: argo-server
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: backstage-incoming
  namespace: backstage
spec:
  ports:
  - name: web
    nodePort: 30083
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: backstage
  type: NodePort