apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: tanuu
  namespace: argocd
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - namespace: '*'
    server: '*'
  sourceRepos:
  - '*'
---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tanuu-setup-app
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  destination:
    name: in-cluster
  project: tanuu
  source:
    directory:
      jsonnet: {}
      recurse: true
    path: setup/argo-applications
    repoURL: https://github.com/tanuuidp/tanuu.git
    targetRevision: main
  syncPolicy:
    automated:
      selfHeal: true
---
apiVersion: v1
kind: Service
metadata:
  name: argocd-incoming
  namespace: argocd
spec:
  ports:
  - name: web
    nodePort: 30081
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app.kubernetes.io/name: argocd-server
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: argo-incoming
  namespace: argo
spec:
  ports:
  - name: web
    nodePort: 30082
    port: 80
    protocol: TCP
    targetPort: 2746
  selector:
    app: argo-server
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: backstage-demo
  namespace: backstage
spec:
  ports:
  - name: web
    nodePort: 30083
    port: 80
    protocol: TCP
    targetPort: 7007
  selector:
    app: backstagedemo
  type: NodePort
---
# kubernetes/backstage.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backstagedemo
  namespace: backstage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backstagedemo
  template:
    metadata:
      labels:
        app: backstagedemo
    spec:
        imagePullSecrets:
        - name: regcred
        containers:
        - name: backstagedemo
          image: tanuuidp/backstage:demo0.0.2
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 7007
          env:
            - name: BACKSTAGE_URL
              value: 'http://127.0.0.1:7007'
          envFrom:
            - secretRef:
                name: backstage-secrets
---
